### ISSUE TITLE
Heads up: What to do if a .NET SDK 2.0-style project file references a type provider like FSharp.Data 

### ISSUE THREAD

**Issue by dsyme** [fsharp/FSharp.Data#1058]
Just a heads up about an issue https://github.com/Microsoft/visualfsharp/issues/3303 which may affect some users of FSharp.Data

With the imminent arrival of .NET SDK 2.0, people are starting to use new .NET SDK-style project files even for .NET Framework programming.  A typical project file looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="3.2.1" />
  </ItemGroup>
</Project>
```
That's it. For the majority of F# code nothing else (besides an install of the .NET SDK) will be required to compile your code.  It's really a very nice and simple story and a lot of people will start converting their F# code to use this new project file format.

However, there is an issue where the F# compiler that ships as part of the .NET SDK doesn't yet correctly support type providers, and so if you use type providers in your project then you need to apply one of the workarounds as listed in https://github.com/Microsoft/visualfsharp/issues/3303. Basically right now you need force the project to use an install of an F# compiler running on .NET Framework/Mono. When that compiler is used instead, then type providers are supported. There are a couple of ways to achieve this as described in that issue.

**Comment by patham9** [comment]
Why is this issue closed although it has not been resolved by now, July 2019?
Downloaded dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz and still the same issue arises. When will it be fixed?

**Comment by dsyme** [comment]
> Why is this issue closed although it has not been resolved by now, June 2019? Downloaded dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz and still the same TypeProvider issue arises. When will it be fixed properly without workarounds and hacks?

Our understanding that this issue was fixed. Do you have a repro steps?

**Comment by Swoorup** [comment]
Still having the same issue when using `dotnet fsi`. What fixes it? .net core 3.0 ?
